name: Hyperion
description: Addon plugin for ProjectKorra
author: Moros
version: ${pluginVersion}
main: me.moros.hyperion.Hyperion
depend: [ProjectKorra]
folia-supported: true
api-version: '1.20'
load: POSTWORLD

permissions:
  bending.admin.overridelock:
    default: false
    description: Allows removing a locksmithing lock even without a matching key.
  bending.command.hyperion:
    default: true
    description: Shows info about Hyperion.
  bending.command.hyperion.reload:
    default: op
    description: Reload the config of Hyperion.
    bending.command.hyperion.checkupdate:
      default: op
      description: Allows the player to manually check for plugin updates.
  hyperion.player:
    default: true
    description: Access to hyperion abilities.
    children:
      bending.ability.AirWheel: true
      bending.ability.Evade: true
      bending.ability.Smokescreen: true
      bending.ability.EarthShards: true
      bending.ability.EarthCling: true
      bending.ability.EarthGlove: true
      bending.ability.EarthGuard: true
      bending.ability.EarthLine: true
      bending.ability.EarthShot: true
      bending.ability.LavaDisk: true
      bending.ability.Locksmithing: true
      bending.ability.MetalCable: true
      bending.ability.FireWave: true
      bending.ability.Bolt: true
      bending.ability.Combustion: true
      bending.ability.IceDrill: true
      bending.ability.IceBreath: true
      bending.ability.IceCrawl: true
